### ISSUE TITLE
node_modules in root, really?

### ISSUE THREAD

**Issue by di3orlive** [zefoy/angular2-perfect-scrollbar#1]
why u didnt add it to .gitignore?

**Comment by RichieRock** [comment]
Hi! This repo is a work in progress, and it will be cleaned up when it's ready.

**Comment by di3orlive** [comment]
hi
i see but it can me in progrees withoun node_modules to 
it just uncomfortable download all this things
cuz it take time...

**Comment by sconix** [comment]
Its faster for devs to download from github than run npm install :) We will release reasonable version in 2-3 weeks once my holiday is over, this was just quick code dump so that we can already use this internally.

**Comment by di3orlive** [comment]
maybe 
but only if they clone it/
and i just download zip) 

and this is terrible
to extract all from archive...

**Comment by sconix** [comment]
I meant that this is better for our internal use since we clone this through npm in our own projects. We will release this through npm and have proper packaging once ready, so closing this issue for now.
